### ISSUE TITLE
list index out of range in group-level hypergraph learning

### ISSUE THREAD

**Issue by FernandoZhuang** [0411tony/HHGR#4]
**Describe the bug**
在`loading the group-level hypergraph learning`部分,运行第二个batch时,出现了list index out of range

**Screenshots**
![Screenshot from 2021-11-02 09-58-17](https://user-images.githubusercontent.com/22760805/139774526-2f468713-533b-4fdf-94e8-eb26a0a64b3e.png)
![Screenshot from 2021-11-02 09-59-00](https://user-images.githubusercontent.com/22760805/139774534-ef26a208-65e0-49d7-ae5e-9fa57ea55a48.png)
![Screenshot from 2021-11-02 09-59-08](https://user-images.githubusercontent.com/22760805/139774538-77149288-880a-4115-a3a6-ddba790360e8.png)

**Comment by jw-zhang-zju** [comment]
Thank you for your question, I did not encounter this problem when training the model. Maybe you can look at the GDataset class in the utils file.
